# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GridSearch1 <- function(x, y, beta00, beta01, beta10, beta11, n) {
    .Call(`_GraphCpClust_GridSearch1`, x, y, beta00, beta01, beta10, beta11, n)
}

